### ISSUE TITLE
Swagger UI does not work for NGNIX rerouting

### ISSUE THREAD

**Issue by pemmenegger** [Hack3rz-Official/annotation-web-service#123]
The same REST request for the NGINX Services (Annotation Service, Prediction Service) does not work via Swagger UI. It works via CURL or via Postman but not via Swagger UI, currently running on localhost:8082. 

Most probably an access error. Check CORS activation or general access of routes from outside for NGINX

**Comment by miczed** [comment]
Quickfix: send requests directly to services (w/o nginx), open the ports

**Comment by miczed** [comment]
Fixed by #174
