### ISSUE TITLE
Specify demo script / use case and test it

### ISSUE THREAD

**Issue by miczed** [Hack3rz-Official/annotation-web-service#154]
- [ ] describe demo procedure / steps
- [ ] ensure that it works in deployed demo
- [ ] ensure that requirements are covered

------

1. load a github repository with all three languages
2. highlight files
3. edit a file and newly highlight it
4. show example of mal-formatted file (snipptes, incomplete file)
5. change language to GO
6. Benchmarking / Performance
7. Show statistics

**Comment by admi22** [comment]
https://www.notion.so/witapp/Presentation-Demo-Script-5a5099de778e4f94ab61502390e49c70
