### ISSUE TITLE
Fix build workflow for predict function

### ISSUE THREAD

**Issue by miczed** [Hack3rz-Official/annotation-web-service#22]
When the predict function is deployed using the GitHub action, the function only has read-access to the azure filesystem.

See this post:
https://docs.microsoft.com/en-us/answers/questions/42218/python-37-file-system-is-read-only.html

So we need to fix the workflow or the source code of the model (`SHModelUtils`) to address this issue.

**Fix for now:** Manually deploy function.

**Comment by pemmenegger** [comment]
since we do not use Azure anymore, this issue will be closed
